name: Build and Publish Library

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build Byte Spot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1

      - name: Copy index.html to 404.html for SPA routing
        run: cp dist/byte-spot/browser/index.html dist/byte-spot/browser/404.html

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/byte-spot/browser
          retention-days: 1

  publish:
    name: Publish Byte Spot
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
